import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1 class="maintitle">Zaynab Lunat</h1>
        </header>
        <nav>
          {/* <Link href="/">
            <a>Home</a>{" "}
          </Link> */}
          <Link href="/">Homepage</Link>
          <Link href="/curious">Curious</Link>
          <Link href="/obsessions">Obsessions</Link>
          <Link href="/ideas">Ideas</Link>
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
